// generated by stringer -type=EventType; DO NOT EDIT

package torctl

import "fmt"

const _EventType_name = "CIRCSTREAM"

var _EventType_index = [...]uint8{0, 4, 10}

func (i EventType) String() string {
	if i < 0 || i+1 >= EventType(len(_EventType_index)) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
